services:
  postgresql:
    image: postgres:16
    container_name: postgresql
    volumes:
      - ./docker/data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DEFAULT}
    ports:
      - "5440:5432"